"""
about.py — About / Disclaimer page.
"""

import streamlit as st


def render():
    st.header("ℹ️ About DiagGen+")

    st.markdown("""
    **DiagGen+** is an educational AI prototype developed as part of an Advanced
    Artificial Intelligence group project. It demonstrates how modern NLP and
    large language model techniques can be combined into an interactive
    medical reasoning system.
    """)

    st.divider()

    st.subheader("⚠️ Important Disclaimer")
    st.error("""
    This tool is for **educational and research purposes only**.

    - It is **not** a certified medical device.
    - It is **not** approved for clinical use.
    - It does **not** replace professional medical advice, diagnosis, or treatment.
    - Always consult a **licensed physician** for any medical concerns.
    """)

    st.divider()

    st.subheader("🔬 How It Works")
    cols = st.columns(3)
    with cols[0]:
        st.markdown("**Step 1 — NLP**")
        st.markdown("Your symptoms are preprocessed using spaCy and represented as rich feature vectors via GloVe/FastText embeddings.")
    with cols[1]:
        st.markdown("**Step 2 — Classification**")
        st.markdown("A fine-tuned BioBERT model classifies the symptoms into probable disease categories with confidence scores.")
    with cols[2]:
        st.markdown("**Step 3 — Reasoning**")
        st.markdown("An LLM generates a doctor-like, step-by-step explanation of the diagnosis using chain-of-thought prompting.")

    st.divider()

    st.subheader("🧠 AI Techniques Used")
    techniques = {
        "NLP": "Text preprocessing, stop-word removal, lemmatisation, GloVe / FastText embeddings",
        "Transformers / LLMs": "BioBERT fine-tuning for symptom-to-disease classification + transfer learning",
        "Generative AI": "Conditional VAE for rare-disease training data augmentation (addresses class imbalance)",
        "Model Training Approaches": "Transfer learning + few-shot learning for novel symptom combinations",
        "Prompt Engineering": "Chain-of-thought + in-context prompting for transparent, step-by-step explanations",
    }
    for tech, desc in techniques.items():
        with st.expander(f"**{tech}**"):
            st.write(desc)

    st.divider()

    st.subheader("📊 Dataset")
    st.markdown("""
    - **Primary**: Health Symptoms and Disease Prediction Dataset (Kaggle, ~25k records)
    - **Secondary**: Symptom2Disease (Hugging Face / Kaggle, 1,200 records, 24 disease classes)
    - All data is **publicly available** and contains **no real patient records (non-PHI)**.
    - Synthetic records generated by the VAE are clearly labelled and used for training augmentation only.
    """)

    st.divider()
    st.caption("DiagGen+ | Advanced AI Group Project 2026 | Educational Use Only")
